### ISSUE TITLE
Week2 Tasks

### ISSUE THREAD

**Issue by herongzheng** [herongzheng/Community-Property-Management-System#4]
host logic, Xingzhou, Pengrui, @pengrui26 @XingzhouTang 
guest logic: Alena @alenasim 
DB：Lan @lan234234 
interface for frontend

@herongzheng

**Comment by herongzheng** [comment]
Est Mon 1pm - 2pm, meeting

**Comment by alenasim** [comment]
Hi guys! Here is a link to the drafted proposal for the interface/technical design in regard to the guest logic. In these slides, I tried to explain my thought process how I came up with this design aspect of the system, and how the proposed workflow would work in resident portal and maintenance. Let me know if you have any questions and let's go over more details in the afternoon meeting! https://docs.google.com/presentation/d/1QMaTYYF-xb3FLTekF5STMtURQVreZ604VTFa19wmCQI/edit#slide=id.p

**Comment by pengrui26** [comment]
Hi guys, here is the logic design for host clients drawn by Xingzhou and me. In order to implement MVP, we marked the necessary features and their structures in this diagram. Please let us know if you have any questions or feedback!
https://boardmix.cn/app/share/CAE.CKPBlQ0gASoQASQq2Yv8jsMgJFjMT004wDAFQAE/uxIA8X

**Comment by herongzheng** [comment]
@alenasim It looks nice to me! 

- [ ] For the issues/maintenance tab, adding the logic to show solved and unsolved issues or show them in sorted order would be a good idea. 

- [ ] You could also think about how the message (about package) could be sent through our platform instead of emails.

- [ ] I didn't find the posts service, where the residents can post anything they like for the public to see

**Comment by herongzheng** [comment]
@pengrui26 @XingzhouTang Good job!

- [ ] I didn't quite get the Package part. It looks like it involves quite a few operations. Can we simplify it? 

- [ ]  For the Posts tab, the chart is clear. How about the logic to stick one post to the top? Logic for Reply and Like? This is P1, we can talk about in the meeting.

- [ ] The Issues tab is P0, adding detailed logic to Reply and Mark would be great.

**Comment by XingzhouTang** [comment]
> @pengrui26 @XingzhouTang Good job!
> 
> * [ ]  I didn't quite get the Package part. It looks like it involves quite a few operations. Can we simplify it?
> * [ ]   For the Posts tab, the chart is clear. How about the logic to stick one post to the top? Logic for Reply and Like? This is P1, we can talk about in the meeting.
> * [ ]  The Issues tab is P0, adding detailed logic to Reply and Mark would be great.

Thanks for your comment. Your suggest is really valuable. 

1 I simplified the package part. My previous logic is that if the host finds the package is not picked up, he/she will send the message again. It is not a high priority, so I deleted it and we may consider it in the future.
2 For the post tab, I updated the logic of top. Once we top a post, we need to list all posts again. 
3 I updated the issue tab. Add logic to check solved/unsolved.

I mark all unnecessary features as grey. Please check the logic design diagram, and let me know if I need to update anything.

**Comment by alenasim** [comment]
Hey great suggestions! I updated the first two bullet points based on your suggestions. For the last bullet point, I didnt include it in the resident section because, based on the project summary, the dashboard is designed to "announce upcoming events, alerts, monthly newsletter, and condo policy" If this is the case, this dashboard logic should belong to the community management with management access.  This is the initial design plan and we can always adjust and change on the fly as well. Let me know what you think.

**Comment by lan234234** [comment]
Hi guys, here is the link to the drafted database design. I've focused on including only the essential tables based on the user journey we mapped out. Please let me know if you have any questions or feedback! https://drive.google.com/file/d/1gCE875mVLbpQaS1cQOVCzBVG54F-wN9o/view?usp=sharing

**Comment by herongzheng** [comment]
Frontend team posted the host page logic and guest page logic @kaiwei666a @gitihabu @LYFHHH12 
[host page.pdf](https://github.com/herongzheng/Community-Property-Management-System/files/12411224/host.page.pdf)

[Guest diagram.pdf](https://github.com/herongzheng/Community-Property-Management-System/files/12411225/Guest.diagram.pdf)

**Comment by herongzheng** [comment]
@kaiwei666a @gitihabu @LYFHHH12
The diagrams show clear logic. It's great! I have my comments as follows

- [ ] you may want to add the host registration logic in the diagram

- [ ] In host page for the issues part, if an issue is received by the lease office, the employee just need to confirm it and no need to reply. Of course, we will keep the "Done" button that indicates if this issue is resolved. Checkout the diagram below

![651692727485_ pic_hd](https://github.com/herongzheng/Community-Property-Management-System/assets/42623080/25492b04-a2ab-4a1f-9e6b-d2518dcc4e73)

- [ ] For both the host and the guest, we want to improve the security that every time someone needs to change the password, the old password must be typed in and checked by the backend server against the record in the database. Please add this logic in the frontend

- [ ] According tot the user journey, we don't need the Dashboard, Chat thread and Schedule tabs. Instead, the Posts tab will cover most of the functionality, where the residents and hosts can post anything they want.
           1. The functionality of posts for both hosts and guests are almost the same. 
           2. only hosts can stick any post to the top and guests cannot. 
           3. hosts can put the announcement here and stick to the top
           4. Our application, at this moment, doesn't provide "schedule" service, just remove it from the chart
           5. Each post/reply can be liked multiple times and the one who add the "like" can also cancel the "like"
           6. Each post can only have one level of replies, e.g. see YouTube comments.

- [ ]  About the payment part, the frontend and backend will meet and see what we can do.

Many thanks!!!

**Comment by herongzheng** [comment]
FYI 
This is my plan for the payment procedure on the host side

![661692728677_ pic_hd](https://github.com/herongzheng/Community-Property-Management-System/assets/42623080/a99dc39d-a98d-4578-a3a3-2d5226253b9a)

**Comment by lan234234** [comment]
Hi guys, here is the link to the updated database design. https://drive.google.com/file/d/1mnMvvWvr61gCL0WLbLA0dt4QonquZIdG/view?usp=sharing

**Comment by pengrui26** [comment]
https://boardmix.cn/app/share/CAE.CKPBlQ0gASoQASQq2Yv8jsMgJFjMT004wDAFQAE/uxIA8X
Here is the revised version, We changed the logic in the issue part and the database selection for the package part.

**Comment by pengrui26** [comment]
Also, we changed the logic for the new resident feature that when a new resident moved in, we delete all the information of the original resident, and create a new user for the new resident.

**Comment by herongzheng** [comment]
resident issue report 

![671692812759_ pic_hd](https://github.com/herongzheng/Community-Property-Management-System/assets/42623080/a7683651-28a8-4b56-bbea-548a2a8a684c)
