### ISSUE TITLE
prep and implementation of services

### ISSUE THREAD

**Issue by herongzheng** [herongzheng/Community-Property-Management-System#7]
**Front end:**
@kaiwei666a @LYFHHH12 @gitihabu 

- [ ] interface b/w frontend and backend
- [ ] utils.js (thoughts)
- [ ] frontend task assignment

**Back end**

- [ ] **model and repository** 

- [ ] Alena: host package and guest message (package)   @alenasim 

- [ ] Pengrui: host management residents tab                   @pengrui26 

- [ ] Lan: issues, host and guest issues                               @lan234234 

- [ ] Xingzhou: host register, login, authenticate,               @XingzhouTang 

- [ ] change_password, chat, AWS S3, fakeController,        @herongzheng

**Comment by gitihabu** [comment]
utils 任务分配：
- [ ] Host：register、authenticate、manage residents;   Resident: authenticate, change password @LYFHHH12 
- [ ] Resident Chat: create, delete, like, unlike, reply; Host Chat: top @kaiwei666a 
- [ ] Package: create; Message; Issue: create, comfirm, close   Kaijie Ma
具体模块分布可见上一条评论中组长附上的图片
